blogging/core/urls.py
from django.conf.urls import url
from blogging.core import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

blogging/profiles/urls.py
from django.conf.urls import url
from blogging.profiles import views

urlpatterns = [
    url(r'^profile/(?P<username>[\w.@+-]+)/$', views.profile, name='profile'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/(?P<username>[\w.@+-]+)/followers$', views.followers, name='followers'),
    url(r'^profile/(?P<username>[\w.@+-]+)/followings$', views.followings, name='followings'),
    url(r'^follow/', views.follow, name='follow'),
    url(r'^unfollow/', views.unfollow, name='unfollow'),
    url(r'^users/$', views.UserListView.as_view(), name='users'),
]

blogging/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url('^', include('blogging.core.urls', namespace='core')),
    url('^', include('blogging.profiles.urls', namespace='profile')),
    url('^', include('blogging.profiles.urls_authentication')),
    url(r'^admin/', admin.site.urls),
]

blogging/core/models.py
from django.db import models


class TimestampedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

blogging/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from blogging.core.models import TimestampedModel


class Post(TimestampedModel, models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=500)

blogging/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from blogging.posts.models import Post


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    biography = models.CharField(max_length=300, blank=True)
    follows = models.ManyToManyField('self',
                                     related_name='followed_by',
                                     symmetrical=False,
                                     blank=True
                                     )

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def follow(self, user_to_follow):
        self.follows.add(user_to_follow)

    def unfollow(self, user_to_unfollow):
        self.follows.remove(user_to_unfollow)

    @property
    def feed(self):
        followings = self.follows.all().values('id')
        followings_ids = [following['id'] for following in followings]
        return Post.objects.filter(user_id__in=followings_ids)\
                           .order_by('-create_at')

    @property
    def posts(self):
        return Post.objects.filter(user=self.user)

    @property
    def followers(self):
        return self.followed_by.all()

    @property
    def followings(self):
        return self.follows.all()

blogging/posts/forms.py
from django.forms import ModelForm, Textarea
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['message']
        widgets = {'message': Textarea(attrs={'rows':4})}

blogging/profiles/forms.py
from django.forms import ModelForm, Textarea
from django.contrib.auth.models import User

from .models import Profile


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['email']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['biography']
        widgets = {'biography': Textarea}

blogging/core/views.py
from django.shortcuts import render, redirect

from blogging.posts.forms import PostForm
from blogging.core.utils import paginator_wrapper


def home(request):
    if not request.user.is_authenticated:
        return redirect('profile:users')

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
    form = PostForm()

    feed_posts = paginator_wrapper(request, request.user.profile.feed, 10)

    context = {'form': form, 'feed_posts': feed_posts}
    return render(request, 'home.html', context)

blogging/posts/views.py
# posts views

blogging/profiles/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.list import ListView

from .forms import ProfileForm, UserForm

from blogging.core.utils import paginator_wrapper


class UserListView(ListView):
    queryset = User.objects.all().order_by('username')
    context_object_name = 'user_list'
    template_name = 'profiles/user_list.html'
    paginate_by = 4


def login(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    template_response = auth_views.login(request)
    if isinstance(template_response, HttpResponseRedirect):
        return redirect('core:home')

    return template_response


def signup(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_views.login(request, user)
            return redirect('core:home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


def profile(request, username):
    user = get_object_or_404(User, username=username)

    followers = [follower.user for follower in user.profile.followed_by.all()[:4]]
    followings = [following.user for following in user.profile.follows.all()[:4]]

    posts = paginator_wrapper(request, user.profile.posts, 10)

    is_followed = request.user in followers or False

    context = {
        'followers': followers,
        'followings': followings,
        'user_profile': user,
        'posts_profile': posts,
        'is_followed': is_followed,
    }

    return render(request, 'profiles/profile.html', context)


@login_required()
def edit_profile(request):
    if request.method == 'POST':
            user_form = UserForm(request.POST, instance=request.user)
            profile_form = ProfileForm(request.POST, instance=request.user.profile)

            if all([user_form.is_valid(),  profile_form.is_valid()]):
                user_form.save()
                profile_form.save()
                return redirect('profile:profile', username=request.user.username)
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(
        request,
        'profiles/edit.html',
        {'user_form': user_form, 'profile_form': profile_form}
    )


def followers(request, username):
    user = get_object_or_404(User, username=username)
    followers = paginator_wrapper(request, user.profile.followers, 10)
    profile = {'username': username}
    context = {'profile': profile, 'followers': followers}
    return render(request, 'profiles/followers.html', context)


def followings(request, username):
    user = get_object_or_404(User, username=username)
    followings = paginator_wrapper(request, user.profile.followings, 10)
    profile = {'username': username}
    context = {'profile': profile, 'followings': followings}
    return render(request, 'profiles/followings.html', context)


@login_required()
def follow(request):
    if request.method == "POST":
        follow_id = request.POST.get('follow', False)
        try:
            user_to_follow = User.objects.get(id=follow_id)
        except User.DoesNotExist:
            return redirect('profile:profile', username=user_to_follow.username)
        else:
            request.user.profile.follow(user_to_follow.profile)
            return redirect('profile:profile', username=user_to_follow.username)


@login_required()
def unfollow(request):
    if request.method == "POST":
        follow_id = request.POST.get('unfollow', False)
        try:
            user_to_unfollow = User.objects.get(id=follow_id)
        except User.DoesNotExist:
            return redirect('profile:profile', username=user_to_unfollow.username)
        else:
            request.user.profile.unfollow(user_to_unfollow.profile)
        return redirect('profile:profile', username=user_to_unfollow.username)

blogging/templates/profiles/edit.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">

        <h2>Edit your information</h2>
        <p>
            <a href="{% url 'password_change' %}">Change your password</a>
        </p>

        <form method="post">
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form profile_form %}
            <button type="submit" class="btn btn-lg btn-primary btn-block">Save</button>
        </form>

    </div>
</div>
 {% endblock %}

blogging/templates/profiles/followers.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">

        <h2>{{ profile.username }}'s followers</h2>
        <div class="list-group">
            {% for profile in followers %}
                <a href="{% url 'profile:profile' username=profile.user.username %}" class="list-group-item">
                    <strong>@{{ profile.user.username }}</strong>
                </a>
            {% endfor %}
        </div>
        {% if followers.has_other_pages %}
            <ul class="pagination">
                {% if followers.has_previous %}
                    <li><a href="?page={{ followers.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in followers.paginator.page_range %}
                    {% if followers.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if followers.has_next %}
                    <li><a href="?page={{ followers.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}

    </div>
</div>
{% endblock %}

blogging/templates/profiles/followings.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">

    <h2>{{ profile.username }}'s followings</h2>
    <div class="list-group">
        {% for profile in followings %}
            <a href="{% url 'profile:profile' username=profile.user.username %}" class="list-group-item">
                <strong>@{{ profile.user.username }}</strong>
            </a>
        {% endfor %}
    </div>
    {% if followings.has_other_pages %}
        <ul class="pagination">
            {% if followings.has_previous %}
                <li><a href="?page={{ followings.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in followings.paginator.page_range %}
                {% if followings.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if followings.has_next %}
                <li><a href="?page={{ followings.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}

    </div>
</div>
{% endblock %}

blogging/templates/profiles/profile.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<div class="row">
    
    <div class="col-sm-3">
        <div>
            {% if user.is_authenticated and user_profile.id == user.id %}
                <a href="{% url 'profile:edit_profile'%}">edit my profile</a>
            {% endif %}
        </div>

        <div>
            {% if user.is_authenticated and user_profile.id != user.id %}
                {% if is_followed %} 
                    <form action="/unfollow/" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="unfollow" value="{{ user_profile.id }}">
                        <input type="submit" value="Unfollow" class="btn btn-primary">
                    </form>
                {% else %}
                    <form action="/follow/" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="follow" value="{{ user_profile.id }}">
                        <input type="submit" value="Follow" class="btn btn-primary">
                    </form>
                {% endif %}
            {% endif %}
        </div>

        <div>
            <h2>Bio</h2>
            <div>
                {{ user_profile.profile.biography }}
            </div>
        </div>

        <h2>Following</h2>
        <div class="list-group">
            {% for following in followings %}
                <a href="{% url 'profile:profile' username=following.username %}" class="list-group-item">
                    <strong>@{{ following.username }}</strong>
                </a>
            {% endfor %}
        </div>
        <a href="{% url 'profile:followings' user_profile.username %}">See all</a>

        <h2>Followers</h2>
        <div class="list-group">
            {% for follower in followers %}
                <a href="{% url 'profile:profile' username=follower.username %}" class="list-group-item">
                    <strong>@{{ follower.username }}</strong>
                </a>
            {% endfor %}
        </div>
        <a href="{% url 'profile:followers' user_profile.username %}">See all</a>
    </div><!-- endcolumn -->    

    <div class="col-sm-7">
        <h2>Posts from {{ user_profile.username }}</h2>
        <div class="list-group">
            {% for post in posts_profile %}
                <div class="list-group-item">
                    <div class="list-group-item-heading">
                        <a href="{% url 'profile:profile' username=post.user.username %}">
                            <strong>@{{ post.user.username }}</strong>
                        </a>
                        <em>{{ post.create_at }}</em>
                    </div>
                    <p class="list-group-item-text">{{ post.message }}</p>
                </div>
            {% endfor %}
        </div>
        <div class="pagination-wrapper">
            {% if posts_profile.has_other_pages %}
                <ul class="pagination">
                    {% if posts_profile.has_previous %}
                        <li><a href="?page={{ posts_profile.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in posts_profile.paginator.page_range %}
                        {% if posts_profile.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if posts_profile.has_next %}
                        <li><a href="?page={{ posts_profile.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>

</div>
{% endblock %}

blogging/templates/profiles/user_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">

        <h2>List of users</h2>
        <div class="list-group">
            {% for user in user_list %}
                <a href="{% url 'profile:profile' username=user.username %}" class="list-group-item">
                    <strong>@{{ user.username }}</strong>
                </a>
            {% endfor %}
        </div>

        <div class="pagination-wrapper">
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>

    </div>
</div>
{% endblock %}

blogging/templates/profiles/users.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">

    <h2>List of users</h2>
    <div class="list-group">
        {% for user in users %}
            <a href="{% url 'profile:profile' username=user.username %}" class="list-group-item">
                <strong>@{{ user.username }}</strong>
            </a>
        {% endfor %}
    </div>

    </div>
</div>
{% endblock %}